name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Generate Gradle Wrapper
        # Este comando cria os arquivos gradlew que estavam faltando
        run: gradle wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        # Agora usamos o ./gradlew (com ponto e barra), que é o jeito correto
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lifeflow-pro-debug
          path: app/build/outputs/apk/debug/app-debug.apk
